apiVersion: apps/v1
kind: Deployment
metadata:
  name: docmost
  namespace: denqxotl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docmost
  template:
    metadata:
      labels:
        app: docmost
    spec:
      initContainers:
        - name: init-create-db
          image: postgres:15
          env:
            - name: PGPASSWORD
              value: password
          command:
            [
              "sh",
              "-c",
              "psql -h postgres -U denqxotl -d postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'docmost'\" | grep -q 1 || psql -h postgres -U denqxotl -d postgres -c \"CREATE DATABASE docmost\""
            ]
      containers:
        - name: docmost
          image: docmost/docmost:latest
          env:
            - name: APP_URL
              value: "http://wiki.rp1"
            - name: DATABASE_URL
              value: "postgres://denqxotl:password@postgres:5432/docmost"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: APP_SECRET
              value: "c4be94db753d4fd944b7a0f059825e2bd3f76c9360ad7d64a7ff1921af437568"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: docmost
  namespace: denqxotl
spec:
  type: ClusterIP
  selector:
    app: docmost
  ports:
    - name: http
      port: 80
      targetPort: 3000

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: replace-assets-path
  namespace: denqxotl
spec:
  replacePathRegex:
    regex: "^/assets/(.*)"
    replacement: "/assets/${1}"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docmost-ingress
  namespace: denqxotl
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: denqxotl-replace-assets-path@kubernetescrd
spec:
  rules:
    - host: wiki.rp1
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docmost
                port:
                  number: 80
